### ISSUE TITLE
使用pycharm运行app.py时提示“以一种访问权限不允许的方式做了一个访问套接字的尝试”。

### ISSUE THREAD

**Issue by greaktang** [ChinaRan0/Simulate-fishing#2]
![微信截图_20231214194715](https://github.com/ChinaRan0/Simulate-fishing/assets/55613090/d51b9959-28e8-4454-9daf-bdc98811b4e5)

**Comment by ChinaRan0** [comment]
端口被占用

**Comment by greaktang** [comment]
> 端口被占用

ok 谢谢 已解决

**Comment by greaktang** [comment]
> 端口被占用

还有一个问题想请教下 如果电脑有多张网卡，比如安装了虚拟网卡，貌似收集的IP和MAC不是太准确了，这个可以解决吗
